notifications:
  email: false
language: objective-c
cache:
  - bundler
  - cocoapods
before_install:
  - gem install cocoapods
  - gem update xcodeproj
  - cd TestAppConsole
  - pod update 
script:
  - pwd
  - ls
  - xcodebuild -workspace TestAppConsole.xcworkspace/ -scheme TestiOS -destination 'platform=iOS Simulator,name=iPhone 6,OS=11.4' -derivedDataPath ./DerivedData -quiet build
  - otool -L ./DerivedData/Build/Products/Debug-iphonesimulator/TestiOS.app/TestiOS
  - xcodebuild -workspace TestAppConsole.xcworkspace/ -scheme TestAppConsole -destination 'platform=macOS,arch=x86_64' -derivedDataPath ./DerivedData -quiet build
  - ./DerivedData/Build/Products/Debug/TestAppConsole
