build:
	xcodebuild -workspace TestAppConsole.xcworkspace/ -scheme TestAppConsole -destination 'platform=macOS,arch=x86_64' -showBuildTimingSummary -derivedDataPath ./DerivedData -quiet clean build
	./DerivedData/Build/Products/Debug/TestAppConsole
