source 'https://github.com/CocoaPods/Specs.git'

target 'TestAppConsole' do
  platform :osx, '10.13'
  pod 'MuckoSwift', '~> 0.1.5'
end

target 'TestiOS' do
  platform :ios, '8.0'
  pod 'MuckoSwift', '~> 0.1.5'
end
