source 'https://github.com/CocoaPods/Specs.git'

def pod_muckoswift
  pod 'MuckoSwift', git: 'https://github.com/wookay/MuckoSwift.git', branch: 'master'
  pod 'SwiftJSONRPC', git: 'https://github.com/wookay/SwiftJSONRPC.git', branch: 'custom'
  pod 'PromiseKit'
  pod 'Alamofire'
end

target 'TestAppConsole' do
  platform :osx, '10.12'
  pod_muckoswift()
end

target 'TestiOS' do
  platform :ios, '8.0'
  pod_muckoswift()
end
